const DEAL_FIELD_CONFIG = [
  ["anrede", "Anrede", "varchar"],
  ["kontoinhaber", "Kontoinhaber", "varchar"],
  ["submission_typ", "Submission Typ", "varchar"],
  ["geburtsdatum", "Geburtsdatum", "date"],
  ["strasse", "Straße", "varchar"],
  ["hausnummer", "Hausnummer", "varchar"],
  ["plz", "PLZ", "varchar"],
  ["ort", "Ort", "varchar"],
  ["neueinzug", "Neueinzug", "varchar"],
  ["einzugsdatum", "Einzugsdatum", "date"],
  ["kundennummer_alt", "Kundennummer Alt", "varchar"],
  ["aktueller_anbieter", "Aktueller Anbieter", "varchar"],
  ["iban", "IBAN", "varchar"],
  ["iban_status", "IBAN Status", "varchar"],
  ["bonitaet", "Bonität", "varchar"],
  ["sparte", "Sparte", "varchar"],
  ["tarif_name", "Tarif Name", "varchar"],
  ["strom_tarif", "Strom Tarif", "varchar"],
  ["strom_verbrauch_kwh", "Strom Verbrauch kWh", "double"],
  ["strom_heizungstyp", "Strom Heizungstyp", "varchar"],
  ["strom_zaehlernummer", "Strom Zählernummer", "varchar"],
  ["strom_malo_id", "Strom MaLo-ID", "varchar"],
  ["strom_zaehler_status", "Strom Zähler Status", "varchar"],
  ["gas_tarif", "Gas Tarif", "varchar"],
  ["gas_verbrauch_kwh", "Gas Verbrauch kWh", "double"],
  ["gas_zaehlernummer", "Gas Zählernummer", "varchar"],
  ["gas_malo_id", "Gas MaLo-ID", "varchar"],
  ["gas_zaehler_status", "Gas Zähler Status", "varchar"],
  ["rechner_status", "rechner_status", "varchar"],
  ["lead_quelle", "Lead-Quelle", "varchar"],
];
